name: "Terraform_staging"

on:
  workflow_run:
    workflows: ["Terraform"]
    types:
      - completed

jobs:
  terraform_staging:
    name: "Terraform_staging"
    runs-on: ubuntu-latest
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
      AWS_REGION: us-east-1

    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: pre-init file
        run: bash ./format_validate_all.sh

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init -var-file="./env/staging/.terraform.tfvars" -backend-config="./env/staging/backend.tfvars"

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file="./env/staging/.terraform.tfvars"

      # - name: Terraform Apply
      #   run: terraform apply -var-file="./env/staging/.terraform.tfvars" --auto-approve

      # - name: Sleep for 2 minutes
      #   run: sleep 120

      - name: Terraform Destroy
        run: terraform destroy --auto-approve -var-file="./env/staging/.terraform.tfvars"

      # - name: Sleep for 2 minutes
      #   run: sleep 120
